server:
  port: 8762
spring:
  application:
    name: spring-cloud-eureka # 服务别名，集群情况一点要相同
eureka:
  instance:
    hostname: 127.0.0.1 # eureka服务端的实力名称
  client:
    fetch-registry: true # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: true # false表示自己不需要向注册中心注册自己
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/  # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(单机版)
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  # 集群版
